// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

module schnova_fu_stage_synth import schnova_synth_pkg::*; #(
  parameter bit               UseFreeList   = 1'b0,
  parameter int unsigned      NofAlus       = 1,
  parameter int unsigned      AluNofRss     = 3,
  parameter int unsigned      NofLsus       = 1,
  parameter int unsigned      LsuNofRss     = 3,
  parameter int unsigned      NofFpus       = 1,
  parameter int unsigned      FpuNofRss     = 2,
  localparam integer unsigned NofOperandIfs = NofAlus * 2 +
                                              NofLsus * 2 +
                                              NofFpus * 3
) (
  input  logic                             clk_i,
  input  logic                             rst_ni,
  /// RS control signals
  input  logic                             restart_i,
  input  logic                             en_superscalar_i,
  // Asserted if all RS are either finishing in this cycle or have already finished
  output logic                             all_rs_finish_o,
  // Commit the dispatch request and allow the downstream passing.
  // The FU blocks do not require a commit signal as when we won't commit we have an exception
  // and thus anyway abort the LxP and reset the RS and RSSs.
  input  logic                             instr_exec_commit_i,
  // FPU-specific commit: same as instr_exec_commit_i but without instr_addr_misaligned_o in its
  // timing cone (FP instructions are never branches, so instr_addr_misaligned_o is always 0).
  input  logic                             fpu_instr_exec_commit_i,
  input  alu_si_disp_req_t                 alu_si_disp_req_i,
  input  logic                             alu_si_disp_req_valid_i,
  output logic                             alu_si_disp_req_ready_o,
  input  alu_rs_disp_req_t   [NofAlus-1:0] alu_rs_disp_reqs_i,
  input  logic               [NofAlus-1:0] alu_rs_disp_reqs_valid_i,
  output logic               [NofAlus-1:0] alu_rs_disp_reqs_ready_o,
  output disp_rsp_t          [NofAlus-1:0] alu_rs_disp_rsp_o,
  output logic               [NofAlus-1:0] alu_rs_full_o,

  input  lsu_si_disp_req_t                 lsu_si_disp_req_i,
  input  logic                             lsu_si_disp_req_valid_i,
  output logic                             lsu_si_disp_req_ready_o,
  input  lsu_rs_disp_req_t   [NofLsus-1:0] lsu_rs_disp_reqs_i,
  input  logic               [NofLsus-1:0] lsu_rs_disp_reqs_valid_i,
  output logic               [NofLsus-1:0] lsu_rs_disp_reqs_ready_o,
  output disp_rsp_t          [NofLsus-1:0] lsu_rs_disp_rsp_o,
  output logic                             lsu_empty_o,
  output logic                             lsu_addr_misaligned_o,
  output data_req_t          [NofLsus-1:0] lsu_dreq_o,
  input  data_rsp_t          [NofLsus-1:0] lsu_drsp_i,
  output logic               [NofLsus-1:0] lsu_rs_full_o,
  input  fpu_si_disp_req_t                 fpu_si_disp_req_i,
  input  logic                             fpu_si_disp_req_valid_i,
  output logic                             fpu_si_disp_req_ready_o,
  input  fpu_rs_disp_req_t   [NofFpus-1:0] fpu_rs_disp_reqs_i,
  input  logic               [NofFpus-1:0] fpu_rs_disp_reqs_valid_i,
  output logic               [NofFpus-1:0] fpu_rs_disp_reqs_ready_o,
  output disp_rsp_t          [NofFpus-1:0] fpu_rs_disp_rsp_o,
  output logic               [NofFpus-1:0] fpu_rs_full_o,
  // Combined status of all FPUs
  output fpnew_pkg::status_t               fpu_status_o,
  output logic                             fpu_status_valid_o,

  // Operand request interface
  output operand_req_t [NofOperandIfs-1:0] op_reqs_o,

  // Operand response interface
  input  operand_t     [NofOperandIfs-1:0] op_rsps_i,
  input  logic         [NofOperandIfs-1:0] op_rsps_valid_i,

  // Reference counter interface
  output logic               [NofAlus-1:0] issue_alu_clr_req_valid_o,
  output refcnt_req_t        [NofAlus-1:0] issue_alu_clr_req_o,
  output logic               [NofLsus-1:0] issue_lsu_clr_req_valid_o,
  output refcnt_req_t        [NofLsus-1:0] issue_lsu_clr_req_o,
  output logic               [NofFpus-1:0] issue_fpu_clr_req_valid_o,
  output refcnt_req_t        [NofFpus-1:0] issue_fpu_clr_req_o,

  // FU results
  output alu_result_t        [NofAlus-1:0] alu_results_o,
  output instr_tag_t         [NofAlus-1:0] alu_results_tag_o,
  output logic               [NofAlus-1:0] alu_results_valid_o,
  input  logic               [NofAlus-1:0] alu_results_ready_i,
  output alu_result_t                      branch_result_o,

  output data_t              [NofLsus-1:0] lsu_results_o,
  output instr_tag_t         [NofLsus-1:0] lsu_results_tag_o,
  output logic               [NofLsus-1:0] lsu_results_valid_o,
  input  logic               [NofLsus-1:0] lsu_results_ready_i,

  output fpu_result_t        [NofFpus-1:0] fpu_results_o,
  output instr_tag_t         [NofFpus-1:0] fpu_results_tag_o,
  output logic               [NofFpus-1:0] fpu_results_valid_o,
  input  logic               [NofFpus-1:0] fpu_results_ready_i
);

  schnova_fu_stage #(
    .XFREPO             (1'b1),
    .UseFreeList        (UseFreeList),
    .MulInAlu0          (1'b1),
    .NofAlus            (NofAlus),
    .AluNofRss          (AluNofRss),
    .AluNofOperands     (2),
    .NofLsus            (NofLsus),
    .LsuNofRss          (LsuNofRss),
    .LsuNofOperands     (2),
    .NofFpus            (NofFpus),
    .FpuNofRss          (FpuNofRss),
    .FpuNofOperands     (3),
    .NofOperandIfs      (NofOperandIfs),
    .XLEN               (XLEN),
    .FLEN               (FLEN),
    .OpLen              (OpLen),
    .AddrWidth          (AddrWidth),
    .DataWidth          (DataWidth),
    .RegAddrWidth       (RegAddrSize),
    .MaxIterationsW     (MaxIterationsW),
    .CaqDepth           (CaqDepth),
    .CaqTagWidth        (CaqTagWidth),
    .NumOutstandingLoads(NumIntOutstandingLoads),
    .NumOutstandingMem  (NumIntOutstandingMem),
    .FPUImplementation  (snitch_cluster_pkg::FPUImplementation[0]),
    .RVF                (1),
    .RVD                (1),
    .XF16               (0),
    .XF16ALT            (0),
    .XF8                (0),
    .XF8ALT             (0),
    .XFVEC              (0),
    .RegisterFPUIn      (0),
    .RegisterFPUOut     (0),
    .producer_id_t      (producer_id_t),
    .slot_id_t          (slot_id_t),
    .rs_id_t            (rs_id_t),
    .alu_si_disp_req_t  (alu_si_disp_req_t),
    .lsu_si_disp_req_t  (lsu_si_disp_req_t),
    .fpu_si_disp_req_t  (fpu_si_disp_req_t),
    .alu_rs_disp_req_t  (alu_rs_disp_req_t),
    .lsu_rs_disp_req_t  (lsu_rs_disp_req_t),
    .fpu_rs_disp_req_t  (fpu_rs_disp_req_t),
    .disp_rsp_t         (disp_rsp_t),
    .fu_data_t          (fu_data_t),
    .instr_tag_t        (instr_tag_t),
    .issue_req_t        (issue_req_t),
    .alu_result_t       (alu_result_t),
    .fpu_result_t       (fpu_result_t),
    .alu_res_val_t      (alu_res_val_t),
    .dreq_t             (data_req_t),
    .drsp_t             (data_rsp_t),
    .phy_id_t           (phy_id_t),
    .operand_req_t      (operand_req_t),
    .operand_t          (operand_t),
    .refcnt_req_t       (refcnt_req_t)
  ) i_fu_stage (
    .clk_i,
    .rst_i(~rst_ni),
    .hard_id_i('0),
    .alu_trace_o(),
    .lsu_trace_o(),
    .fpu_trace_o(),
    .alu_retire_trace_o(),
    .lsu_load_retire_trace_o(),
    .lsu_store_retire_trace_o(),
    .fpu_retire_trace_o(),
    .restart_i,
    .en_superscalar_i,
    .all_rs_finish_o,
    .instr_exec_commit_i,
    .fpu_instr_exec_commit_i,
    .alu_si_disp_req_i,
    .alu_si_disp_req_valid_i,
    .alu_si_disp_req_ready_o,
    .alu_rs_disp_reqs_i,
    .alu_rs_disp_reqs_valid_i,
    .alu_rs_disp_reqs_ready_o,
    .alu_rs_disp_rsp_o,
    .alu_rs_full_o,
    .lsu_si_disp_req_i,
    .lsu_si_disp_req_valid_i,
    .lsu_si_disp_req_ready_o,
    .lsu_rs_disp_reqs_i,
    .lsu_rs_disp_reqs_valid_i,
    .lsu_rs_disp_reqs_ready_o,
    .lsu_rs_disp_rsp_o,
    .lsu_empty_o,
    .lsu_addr_misaligned_o,
    .lsu_dreq_o,
    .lsu_drsp_i,
    .lsu_rs_full_o,
    .caq_addr_i('0),
    .caq_track_write_i('0),
    .caq_req_valid_i('0),
    .caq_req_ready_o(),
    .caq_rsp_valid_i('0),
    .caq_rsp_valid_o(),
    .fpu_si_disp_req_i,
    .fpu_si_disp_req_valid_i,
    .fpu_si_disp_req_ready_o,
    .fpu_rs_disp_reqs_i,
    .fpu_rs_disp_reqs_valid_i,
    .fpu_rs_disp_reqs_ready_o,
    .fpu_rs_disp_rsp_o,
    .fpu_rs_full_o,
    .fpu_status_o,
    .fpu_status_valid_o,
    .op_reqs_o,
    .op_rsps_i,
    .op_rsps_valid_i,
    .issue_alu_clr_req_valid_o,
    .issue_alu_clr_req_o,
    .issue_lsu_clr_req_valid_o,
    .issue_lsu_clr_req_o,
    .issue_fpu_clr_req_valid_o,
    .issue_fpu_clr_req_o,
    .alu_results_o,
    .alu_results_tag_o,
    .alu_results_valid_o,
    .alu_results_ready_i,
    .branch_result_o,
    .lsu_results_o,
    .lsu_results_tag_o,
    .lsu_results_valid_o,
    .lsu_results_ready_i,
    .fpu_results_o,
    .fpu_results_tag_o,
    .fpu_results_valid_o,
    .fpu_results_ready_i
  );

endmodule
