// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

module schnizo_res_stat_synth #(
  parameter int unsigned NofRss = 4,
  parameter int unsigned NofOperands = 2,
  parameter int unsigned ConsumerCount = 32,
  parameter bit          UseSram = 1'b0
) (
  input  logic                                              clk_i,
  input  logic                                              rst_ni,
  input  logic                                              restart_i,
  input  schnizo_pkg::loop_state_e                          loop_state_i,
  input  logic [schnizo_synth_pkg::MaxIterationsW-1:0]      lep_iterations_i,
  input  logic                                              goto_lcp2_i,
  output logic                                              loop_finish_o,
  output logic                                              rs_full_o,
  input  logic                                              fu_busy_i,
  input  schnizo_synth_pkg::disp_req_t                      disp_req_i,
  input  logic                                              disp_req_valid_i,
  output logic                                              disp_req_ready_o,
  input  logic                                              instr_exec_commit_i,
  output schnizo_synth_pkg::disp_rsp_t                      disp_rsp_o,
  output schnizo_synth_pkg::issue_req_t                     issue_req_o,
  output logic                                              issue_req_valid_o,
  input  logic                                              issue_req_ready_i,
  output logic                                              instr_exec_commit_o,
  input  schnizo_synth_pkg::alu_result_t                    result_i,
  input  schnizo_pkg::instr_tag_t                           result_tag_i,
  input  logic                                              result_valid_i,
  output logic                                              result_ready_o,
  output schnizo_synth_pkg::alu_result_t                    rf_wb_result_o,
  output schnizo_pkg::instr_tag_t                           rf_wb_tag_o,
  output logic                                              rf_wb_valid_o,
  input  logic                                              rf_wb_ready_i,
  output schnizo_synth_pkg::operand_req_t [NofRss-1:0]      available_results_o,
  output schnizo_synth_pkg::operand_req_t [NofOperands-1:0] op_reqs_o,
  output logic                            [NofOperands-1:0] op_reqs_valid_o,
  input  logic                            [NofOperands-1:0] op_reqs_ready_i,
  input  schnizo_synth_pkg::res_req_t     [NofRss-1:0]      res_reqs_i,
  input  logic                            [NofRss-1:0]      res_reqs_valid_i,
  output logic                            [NofRss-1:0]      res_reqs_ready_o,
  output schnizo_synth_pkg::res_rsp_t     [NofRss-1:0]      res_rsps_o,
  output logic                            [NofRss-1:0]      res_rsps_valid_o,
  input  logic                            [NofRss-1:0]      res_rsps_ready_i,
  input  schnizo_synth_pkg::operand_t     [NofOperands-1:0] op_rsps_i,
  input  logic                            [NofOperands-1:0] op_rsps_valid_i,
  output logic                            [NofOperands-1:0] op_rsps_ready_o
);

  schnizo_synth_pkg::producer_id_t producer_id;
  assign producer_id = schnizo_synth_pkg::producer_id_t'{
    slot_id: '0,
    rs_id:   '0
  };
  
  schnizo_res_stat #(
    .NofRss(NofRss),
    .NofOperands(NofOperands),
    .NofResRspIfs(NofRss),
    .ConsumerCount(ConsumerCount),
    .RegAddrWidth(schnizo_pkg::RegAddrSize),
    .MaxIterationsW(schnizo_synth_pkg::MaxIterationsW),
    .UseSram(UseSram),
    .disp_req_t(schnizo_synth_pkg::disp_req_t),
    .disp_rsp_t(schnizo_synth_pkg::disp_rsp_t),
    .issue_req_t(schnizo_synth_pkg::issue_req_t),
    .result_t(schnizo_synth_pkg::alu_result_t),
    .result_tag_t(schnizo_pkg::instr_tag_t),
    .producer_id_t(schnizo_synth_pkg::producer_id_t),
    .slot_id_t(schnizo_synth_pkg::slot_id_t),
    .operand_req_t(schnizo_synth_pkg::operand_req_t),
    .operand_t(schnizo_synth_pkg::operand_t),
    .res_req_t(schnizo_synth_pkg::res_req_t),
    .dest_mask_t(schnizo_synth_pkg::dest_mask_t),
    .res_rsp_t(schnizo_synth_pkg::res_rsp_t)
  ) i_res_stat (
    .clk_i,
    .rst_i(!rst_ni),
    .producer_id_i(producer_id),
    .restart_i,
    .loop_state_i,
    .lep_iterations_i,
    .goto_lcp2_i,
    .loop_finish_o,
    .rs_full_o,
    .fu_busy_i,
    .disp_req_i,
    .disp_req_valid_i,
    .disp_req_ready_o,
    .instr_exec_commit_i,
    .disp_rsp_o,
    .issue_req_o,
    .issue_req_valid_o,
    .issue_req_ready_i,
    .instr_exec_commit_o,
    .result_i,
    .result_tag_i,
    .result_valid_i,
    .result_ready_o,
    .rf_wb_result_o,
    .rf_wb_tag_o,
    .rf_wb_valid_o,
    .rf_wb_ready_i,
    .available_results_o,
    .op_reqs_o,
    .op_reqs_valid_o,
    .op_reqs_ready_i,
    .res_reqs_i,
    .res_reqs_valid_i,
    .res_reqs_ready_o,
    .res_rsps_o,
    .res_rsps_valid_o,
    .res_rsps_ready_i,
    .op_rsps_i,
    .op_rsps_valid_i,
    .op_rsps_ready_o
  );

endmodule