// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

module schnizo_fu_stage_synth #(
  parameter bit          Xfrep           = 1,
  parameter bit          MulInAlu0       = 1'b1,
  parameter int unsigned NofAlus         = 1,
  parameter int unsigned NofLsus         = 1,
  parameter int unsigned NofFpus         = 1,
  parameter int unsigned NofRss          = 1
) (
  input  logic                                                    clk_i,
  input  logic                                                    rst_ni,
  input  logic                                                    restart_i,
  input  schnizo_pkg::loop_state_e                                loop_state_i,
  input  logic [schnizo_pkg::FrepMaxItersWidth-1:0]               lep_iterations_i,
  input  logic                                                    goto_lcp2_i,
  output logic                                                    all_rs_finish_o,
  input  schnizo_synth_pkg::disp_req_t                            disp_req_i,
  input  logic                                                    instr_exec_commit_i,
  input  logic               [NofAlus-1:0]                        alu_disp_reqs_valid_i,
  output logic               [NofAlus-1:0]                        alu_disp_reqs_ready_o,
  output schnizo_synth_pkg::disp_rsp_t          [NofAlus-1:0]     alu_disp_rsp_o,
  output logic               [NofAlus-1:0]                        alu_rs_full_o,
  input  logic               [NofLsus-1:0]                        lsu_disp_reqs_valid_i,
  output logic               [NofLsus-1:0]                        lsu_disp_reqs_ready_o,
  output schnizo_synth_pkg::disp_rsp_t          [NofLsus-1:0]     lsu_disp_rsp_o,
  output logic                                                    lsu_empty_o,
  output logic                                                    lsu_addr_misaligned_o,
  output schnizo_synth_pkg::data_req_t              [NofLsus-1:0] lsu_dreq_o,
  input  schnizo_synth_pkg::data_rsp_t              [NofLsus-1:0] lsu_drsp_i,
  output logic               [NofLsus-1:0]                        lsu_rs_full_o,
  input  logic               [NofFpus-1:0]                        fpu_disp_reqs_valid_i,
  output logic               [NofFpus-1:0]                        fpu_disp_reqs_ready_o,
  output schnizo_synth_pkg::disp_rsp_t          [NofFpus-1:0]     fpu_disp_rsp_o,
  output logic               [NofFpus-1:0]                        fpu_rs_full_o,
  output fpnew_pkg::status_t                                      fpu_status_o,
  output logic                                                    fpu_status_valid_o,
  output schnizo_synth_pkg::alu_result_t                          alu_wb_result_o,
  output schnizo_pkg::instr_tag_t                                 alu_wb_result_tag_o,
  output logic                                                    alu_wb_result_valid_o,
  input  logic                                                    alu_wb_result_ready_i,
  output schnizo_synth_pkg::alu_result_t                          branch_result_o,
  output schnizo_synth_pkg::data_t                                lsu_wb_result_o,
  output schnizo_pkg::instr_tag_t                                 lsu_wb_result_tag_o,
  output logic                                                    lsu_wb_result_valid_o,
  input  logic                                                    lsu_wb_result_ready_i,
  output logic [schnizo_synth_pkg::FLEN-1:0]                      fpu_wb_result_o,
  output schnizo_pkg::instr_tag_t                                 fpu_wb_result_tag_o,
  output logic                                                    fpu_wb_result_valid_o,
  input  logic                                                    fpu_wb_result_ready_i
);

  localparam integer unsigned NofOperandIfs = NofAlus * 2 +
                                              NofLsus * 3 +
                                              NofFpus * 3;

  localparam integer unsigned NofResReqIfs = NofAlus + NofLsus + NofFpus;

  localparam integer unsigned NofResRspIfs = NofAlus * NofRss +
                                             NofLsus * NofRss +
                                             NofFpus * NofRss;

  schnizo_fu_stage #(
    .Xfrep(Xfrep),
    .MulInAlu0(MulInAlu0),
    .NofAlus(NofAlus),
    .AluNofRss(NofRss),
    .AluNofOperands(2),
    .AluNofOpPorts(1),
    .AluNofResReqIfs(1),
    .AluNofResRspIfs(NofRss),
    .NofLsus(NofLsus),
    .LsuNofRss(NofRss),
    .LsuNofOperands(3),
    .LsuNofOpPorts(1),
    .LsuNofResReqIfs(1),
    .LsuNofResRspIfs(NofRss),
    .NofFpus(NofFpus),
    .FpuNofRss(NofRss),
    .FpuNofOperands(3),
    .FpuNofOpPorts(1),
    .FpuNofResReqIfs(1),
    .FpuNofResRspIfs(NofRss),
    .NofOperandIfs(NofOperandIfs),
    .NofResReqIfs(NofResReqIfs),
    .NofResRspIfs(NofResRspIfs),
    .XLEN(schnizo_synth_pkg::XLEN),
    .FLEN(schnizo_synth_pkg::FLEN),
    .OpLen(schnizo_synth_pkg::OpLen),
    .AddrWidth(schnizo_synth_pkg::AddrWidth),
    .DataWidth(schnizo_synth_pkg::DataWidth),
    .RegAddrWidth(schnizo_pkg::RegAddrSize),
    .MaxIterationsW(schnizo_pkg::FrepMaxItersWidth),
    .CaqDepth(8),
    .CaqTagWidth(16),
    .NumOutstandingLoads(schnizo_synth_pkg::NumIntOutstandingLoads),
    .NumOutstandingMem(schnizo_synth_pkg::NumIntOutstandingMem),
    .FPUImplementation(schnizo_synth_pkg::FpuImplementation),
    .RVF(1),
    .RVD(1),
    .XF16(0),
    .XF16ALT(0),
    .XF8(0),
    .XF8ALT(0),
    .XFVEC(0),
    .RegisterFPUIn(0),
    .RegisterFPUOut(0),
    .producer_id_t(schnizo_synth_pkg::producer_id_t),
    .slot_id_t(schnizo_synth_pkg::slot_id_t),
    .rs_id_t(schnizo_synth_pkg::rs_id_t),
    .operand_id_t(schnizo_synth_pkg::operand_id_t),
    .disp_req_t(schnizo_synth_pkg::disp_req_t),
    .disp_rsp_t(schnizo_synth_pkg::disp_rsp_t),
    .fu_data_t(schnizo_synth_pkg::fu_data_t),
    .instr_tag_t(schnizo_pkg::instr_tag_t),
    .alu_result_t(schnizo_synth_pkg::alu_result_t),
    .alu_res_val_t(schnizo_synth_pkg::alu_res_val_t),
    .dreq_t(schnizo_synth_pkg::data_req_t),
    .drsp_t(schnizo_synth_pkg::data_rsp_t)
  ) i_fu_stage (
    .clk_i,
    .rst_i(!rst_ni),
    .hard_id_i('0),
    .restart_i,
    .loop_state_i,
    .lep_iterations_i,
    .goto_lcp2_i,
    .all_rs_finish_o,
    .disp_req_i,
    .instr_exec_commit_i,
    .alu_trace_o(),
    .lsu_trace_o(),
    .fpu_trace_o(),
    .alu_retire_trace_o(),
    .lsu_retire_trace_o(),
    .fpu_retire_trace_o(),
    .alu_disp_reqs_valid_i,
    .alu_disp_reqs_ready_o,
    .alu_disp_rsp_o,
    .alu_rs_full_o,
    .lsu_disp_reqs_valid_i,
    .lsu_disp_reqs_ready_o,
    .lsu_disp_rsp_o,
    .lsu_empty_o,
    .lsu_addr_misaligned_o,
    .lsu_dreq_o,
    .lsu_drsp_i,
    .lsu_rs_full_o,
    .caq_addr_i('0),
    .caq_track_write_i('0),
    .caq_req_valid_i('0),
    .caq_req_ready_o(),
    .caq_rsp_valid_i('0),
    .caq_rsp_valid_o(),
    .fpu_disp_reqs_valid_i,
    .fpu_disp_reqs_ready_o,
    .fpu_disp_rsp_o,
    .fpu_rs_full_o,
    .fpu_status_o,
    .fpu_status_valid_o,
    .alu_wb_result_o,
    .alu_wb_result_tag_o,
    .alu_wb_result_valid_o,
    .alu_wb_result_ready_i,
    .branch_result_o,
    .lsu_wb_result_o,
    .lsu_wb_result_tag_o,
    .lsu_wb_result_valid_o,
    .lsu_wb_result_ready_i,
    .fpu_wb_result_o,
    .fpu_wb_result_tag_o,
    .fpu_wb_result_valid_o,
    .fpu_wb_result_ready_i
  );

endmodule