// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

module schnizo_fu_stage_synth #(
  // FP extension enable bits
  parameter bit          Xfrep           = 1,
  parameter bit          MulInAlu0       = 1'b1,
  parameter bit          RVF             = 1,
  parameter bit          RVD             = 1,
  parameter bit          XF16            = 1,
  parameter bit          XF16ALT         = 1,
  parameter bit          XF8             = 1,
  parameter bit          XF8ALT          = 1,
  parameter bit          XFVEC           = 1,
  // RVV (vector) enable - activates VFU/VLSU paths
  parameter bit          RVV             = 1,
  // LSU outstanding transaction limits
  parameter int unsigned NumOutstandingLoads = 4,
  parameter int unsigned NumOutstandingMem   = 4,
  // Scalar ALU configuration
  parameter int unsigned NofAlus         = 3,
  parameter int unsigned NofAluRss       = 3,
  parameter int unsigned NofAluConstants = 8,
  // Scalar LSU configuration
  parameter int unsigned NofLsus         = 3,
  parameter int unsigned NofLsuRss       = 3,
  parameter int unsigned NofLsuConstants = 6,
  // Scalar FPU configuration
  parameter int unsigned NofFpus         = 1,
  parameter int unsigned NofFpuRss       = 4,
  parameter int unsigned NofFpuConstants = 6,
  // Vector VFU / VLSU unit counts
  parameter int unsigned NofVFU          = 1,
  parameter int unsigned NofVLSU         = 1,
  // Spatz sub-unit counts (inside each schnizo_vfu)
  parameter int unsigned NumSpatzFPUs    = 4,
  parameter int unsigned NumSpatzIPUs    = 1,
  // Vector RS depths
  parameter int unsigned NofVfuRss       = 8,
  parameter int unsigned NofVlsuRss      = 6,
  // Vector constant-queue depths
  parameter int unsigned NofVfuConstants = 6,
  parameter int unsigned NofVlsuConstants = 2
) (
  input  logic                                                    clk_i,
  input  logic                                                    rst_ni,
  input  logic                                                    restart_i,
  input  schnizo_pkg::loop_state_e                                loop_state_i,
  input  logic [schnizo_pkg::FrepMaxItersWidth-1:0]               lep_iterations_i,
  input  logic                                                    goto_lcp2_i,
  output logic                                                    all_rs_finish_o,
  input  schnizo_synth_pkg::disp_req_t                            disp_req_i,
  input  logic                                                    instr_exec_commit_i,
  input  logic               [NofAlus-1:0]                        alu_disp_reqs_valid_i,
  output logic               [NofAlus-1:0]                        alu_disp_reqs_ready_o,
  output schnizo_synth_pkg::disp_rsp_t          [NofAlus-1:0]     alu_disp_rsp_o,
  output logic               [NofAlus-1:0]                        alu_rs_full_o,
  input  logic               [NofLsus-1:0]                        lsu_disp_reqs_valid_i,
  output logic               [NofLsus-1:0]                        lsu_disp_reqs_ready_o,
  output schnizo_synth_pkg::disp_rsp_t          [NofLsus-1:0]     lsu_disp_rsp_o,
  output logic                                                    lsu_empty_o,
  output logic                                                    lsu_addr_misaligned_o,
  output schnizo_synth_pkg::data_req_t              [NofLsus-1:0] lsu_dreq_o,
  input  schnizo_synth_pkg::data_rsp_t              [NofLsus-1:0] lsu_drsp_i,
  output logic               [NofLsus-1:0]                        lsu_rs_full_o,
  input  logic               [NofFpus-1:0]                        fpu_disp_reqs_valid_i,
  output logic               [NofFpus-1:0]                        fpu_disp_reqs_ready_o,
  output schnizo_synth_pkg::disp_rsp_t          [NofFpus-1:0]     fpu_disp_rsp_o,
  output logic               [NofFpus-1:0]                        fpu_rs_full_o,
  output fpnew_pkg::status_t                                      fpu_status_o,
  output logic                                                    fpu_status_valid_o,
  output schnizo_synth_pkg::alu_result_t                          alu_wb_result_o,
  output schnizo_pkg::instr_tag_t                                 alu_wb_result_tag_o,
  output logic                                                    alu_wb_result_valid_o,
  input  logic                                                    alu_wb_result_ready_i,
  output schnizo_synth_pkg::alu_result_t                          branch_result_o,
  output schnizo_synth_pkg::data_t                                lsu_wb_result_o,
  output schnizo_pkg::instr_tag_t                                 lsu_wb_result_tag_o,
  output logic                                                    lsu_wb_result_valid_o,
  input  logic                                                    lsu_wb_result_ready_i,
  output logic [schnizo_synth_pkg::FLEN-1:0]                      fpu_wb_result_o,
  output schnizo_pkg::instr_tag_t                                 fpu_wb_result_tag_o,
  output logic                                                    fpu_wb_result_valid_o,
  input  logic                                                    fpu_wb_result_ready_i
);

  localparam int unsigned NumSpatzFUs         = (NumSpatzFPUs > NumSpatzIPUs) ? NumSpatzFPUs : NumSpatzIPUs;
  localparam int unsigned NumMemPortsPerSpatz = NumSpatzFUs;

  localparam integer unsigned NofOperandIfs = NofAlus * 2 +
                                              NofLsus * 4 +
                                              NofFpus * 3 +
                                              (RVV ? NofVLSU * 2 + NofVFU * 2 : 0);

  localparam integer unsigned NofResReqIfs = NofAlus + NofLsus + NofFpus +
                                             (RVV ? NofVLSU + NofVFU : 0);

  schnizo_fu_stage #(
    .Xfrep(Xfrep),
    .MulInAlu0(MulInAlu0),
    .NofAlus(NofAlus),
    .AluNofRss(NofAluRss),
    .AluNofConstants(NofAluConstants),
    .AluNofOperands(2),
    .AluNofResReqIfs(1),
    .AluNofResRspPorts(1),
    .NofLsus(NofLsus),
    .LsuNofRss(NofLsuRss),
    .LsuNofConstants(NofLsuConstants),
    .LsuNofOperands(4),
    .LsuNofResReqIfs(1),
    .LsuNofResRspPorts(1),
    .NofFpus(NofFpus),
    .FpuNofRss(NofFpuRss),
    .FpuNofConstants(NofFpuConstants),
    .FpuNofOperands(3),
    .FpuNofResReqIfs(1),
    .FpuNofResRspPorts(1),
    .VlsuNofRss(NofVlsuRss),
    .VlsuNofConstants(NofVlsuConstants),
    .VlsuNofOperands(2),
    .VlsuNofResRspPorts(1),
    .VfuNofRss(NofVfuRss),
    .VfuNofConstants(NofVfuConstants),
    .VfuNofOperands(2),
    .VfuNofResRspPorts(1),
    .NofVFU(NofVFU),
    .NofVLSU(NofVLSU),
    .NumSpatzFPUs(NumSpatzFPUs),
    .NumSpatzIPUs(NumSpatzIPUs),
    .NofOperandIfs(NofOperandIfs),
    .NofResReqIfs(NofResReqIfs),
    .RVV(RVV),
    .XLEN(schnizo_synth_pkg::XLEN),
    .FLEN(schnizo_synth_pkg::FLEN),
    .OpLen(schnizo_synth_pkg::OpLen),
    .AddrWidth(schnizo_synth_pkg::AddrWidth),
    .DataWidth(schnizo_synth_pkg::DataWidth),
    .RegAddrWidth(schnizo_pkg::RegAddrSize),
    .MaxIterationsW(schnizo_pkg::FrepMaxItersWidth),
    .CaqDepth(8),
    .CaqTagWidth(16),
    .NumOutstandingLoads(NumOutstandingLoads),
    .NumOutstandingMem(NumOutstandingMem),
    .FPUImplementation(schnizo_synth_pkg::FpuImplementation),
    .RVF(RVF),
    .RVD(RVD),
    .XF16(XF16),
    .XF16ALT(XF16ALT),
    .XF8(XF8),
    .XF8ALT(XF8ALT),
    .XFVEC(XFVEC),
    .RegisterFPUIn(0),
    .RegisterFPUOut(0),
    .producer_id_t(schnizo_synth_pkg::producer_id_t),
    .slot_id_t(schnizo_synth_pkg::slot_id_t),
    .rs_id_t(schnizo_synth_pkg::rs_id_t),
    .operand_id_t(schnizo_synth_pkg::operand_id_t),
    .disp_req_t(schnizo_synth_pkg::disp_req_t),
    .disp_rsp_t(schnizo_synth_pkg::disp_rsp_t),
    .fu_data_t(schnizo_synth_pkg::fu_data_t),
    .instr_tag_t(schnizo_pkg::instr_tag_t),
    .alu_result_t(schnizo_synth_pkg::alu_result_t),
    .alu_res_val_t(schnizo_synth_pkg::alu_res_val_t),
    .dreq_t(schnizo_synth_pkg::data_req_t),
    .drsp_t(schnizo_synth_pkg::data_rsp_t),
    .tcdm_req_chan_t(schnizo_synth_pkg::tcdm_req_chan_t),
    .tcdm_rsp_chan_t(schnizo_synth_pkg::tcdm_rsp_chan_t),
    .tcdm_req_t(schnizo_synth_pkg::tcdm_req_t),
    .tcdm_rsp_t(schnizo_synth_pkg::tcdm_rsp_t)
  ) i_fu_stage (
    .clk_i,
    .rst_i(!rst_ni),
    .hard_id_i('0),
    .restart_i,
    .loop_state_i,
    .lep_iterations_i,
    .goto_lcp2_i,
    .all_rs_finish_o,
    .disp_req_i,
    .instr_exec_commit_i,
    .fpu_instr_exec_commit_i(instr_exec_commit_i),
    .alu_trace_o(),
    .lsu_trace_o(),
    .fpu_trace_o(),
    .vfu_trace_o(),
    .vlsu_trace_o(),
    .alu_retire_trace_o(),
    .lsu_retire_trace_o(),
    .fpu_retire_trace_o(),
    .vfu_retire_trace_o(),
    .vlsu_retire_trace_o(),
    .alu_disp_reqs_valid_i,
    .alu_disp_reqs_ready_o,
    .alu_disp_rsp_o,
    .alu_rs_full_o,
    .lsu_disp_reqs_valid_i,
    .lsu_disp_reqs_ready_o,
    .lsu_disp_rsp_o,
    .lsu_empty_o,
    .lsu_addr_misaligned_o,
    .lsu_dreq_o,
    .lsu_drsp_i,
    .lsu_rs_full_o,
    .caq_addr_i('0),
    .caq_track_write_i('0),
    .caq_req_valid_i('0),
    .caq_req_ready_o(),
    .caq_rsp_valid_i('0),
    .caq_rsp_valid_o(),
    .fpu_disp_reqs_valid_i,
    .fpu_disp_reqs_ready_o,
    .fpu_disp_rsp_o,
    .fpu_rs_full_o,
    .fpu_status_o,
    .fpu_status_valid_o,
    .alu_wb_result_o,
    .alu_wb_result_tag_o,
    .alu_wb_result_valid_o,
    .alu_wb_result_ready_i,
    .branch_result_o,
    .lsu_wb_result_o,
    .lsu_wb_result_tag_o,
    .lsu_wb_result_valid_o,
    .lsu_wb_result_ready_i,
    .fpu_wb_result_o,
    .fpu_wb_result_tag_o,
    .fpu_wb_result_valid_o,
    .fpu_wb_result_ready_i,
    .vfu_disp_reqs_valid_i('0),
    .vfu_disp_reqs_ready_o(),
    .vfu_disp_rsp_o(),
    .vfu_loop_finish_o(),
    .vfu_rs_full_o(),
    .vfu_wb_result_o(),
    .vfu_wb_result_tag_o(),
    .vfu_wb_result_valid_o(),
    .vfu_wb_result_ready_i('1),
    .vfu_tcdm_req_o(),
    .vfu_tcdm_rsp_i('0)
  );

endmodule
