// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

module snitch_synth (
	input  logic                                       clk_i,
	input  logic                                       rst_ni,
	input  logic [31:0]                                hart_id_i,
	input  snitch_pkg::interrupts_t                    irq_i,
	output logic                                       flush_i_valid_o,
	input  logic                                       flush_i_ready_i,
	output schnizo_synth_pkg::addr_t                   inst_addr_o,
	output logic                                       inst_cacheable_o,
	input  logic [31:0]                                inst_data_i,
	output logic                                       inst_valid_o,
	input  logic                                       inst_ready_i,
	output schnizo_synth_pkg::acc_req_t                acc_qreq_o,
	output logic                                       acc_qvalid_o,
	input  logic                                       acc_qready_i,
	input  schnizo_synth_pkg::acc_resp_t               acc_prsp_i,
	input  logic                                       acc_pvalid_i,
	output logic                                       acc_pready_o,
	output schnizo_synth_pkg::data_req_t               data_req_o,
	input  schnizo_synth_pkg::data_rsp_t               data_rsp_i,
	output fpnew_pkg::roundmode_e                      fpu_rnd_mode_o,
	output fpnew_pkg::fmt_mode_t                       fpu_fmt_mode_o,
	input  fpnew_pkg::status_t                         fpu_status_i,
  	input  logic                                       caq_pvalid_i,
	output snitch_pkg::core_events_t                   core_events_o,
	output logic                                       barrier_o,
	input  logic                                       barrier_i
);

	snitch #(
		.BootAddr(schnizo_synth_pkg::BootAddr),
		.AddrWidth(schnizo_synth_pkg::AddrWidth),
		.DataWidth(schnizo_synth_pkg::DataWidth),
		.RVE(0),
		.Xdma(0),
		.Xssr(0),
		.Xcopift(0),
		.FP_EN(1),
		.RVF(1),
		.RVD(1),
		.XF16(0),
		.XF16ALT(0),
		.XF8(0),
		.XF8ALT(0),
		.XDivSqrt(0),
		.XFDOTP(0),
		.XFAUX(0),
		.XFVEC(0),
		.FLEN(schnizo_synth_pkg::DataWidth),
		.VMSupport(0),
		.Xpulppostmod(0),
		.Xpulpabs(0),
		.Xpulpbitop(0),
		.Xpulpbr(0),
		.Xpulpclip(0),
		.Xpulpmacsi(0),
		.Xpulpminmax(0),
		.Xpulpslet(0),
		.Xpulpvect(0),
		.Xpulpvectshufflepack(0),
		.Xpulpv2(0),
		.dreq_t(schnizo_synth_pkg::data_req_t),
		.drsp_t(schnizo_synth_pkg::data_rsp_t),
		.acc_req_t(schnizo_synth_pkg::acc_req_t),
		.acc_resp_t(schnizo_synth_pkg::acc_resp_t),
		.EnableXif(0),
		.x_issue_req_t(snitch_cluster_pkg::x_issue_req_t),
		.x_issue_resp_t(snitch_cluster_pkg::x_issue_resp_t),
		.x_register_t(snitch_cluster_pkg::x_register_t),
		.x_commit_t(snitch_cluster_pkg::x_commit_t),
		.x_result_t(snitch_cluster_pkg::x_result_t),
		.NumIntOutstandingLoads(schnizo_synth_pkg::NumIntOutstandingLoads),
		.NumIntOutstandingMem(schnizo_synth_pkg::NumIntOutstandingMem),
		.SnitchPMACfg(snitch_cluster_pkg::SnitchPMACfg),
		.CaqDepth(8),
		.CaqTagWidth(16),
		.DebugSupport(0)
	) i_snitch (
		.clk_i,
		.rst_i(!rst_ni),
		.hart_id_i,
		.irq_i,
		.flush_i_valid_o,
		.flush_i_ready_i,
		.inst_addr_o,
		.inst_cacheable_o,
		.inst_data_i,
		.inst_valid_o,
		.inst_ready_i,
		.acc_qreq_o,
		.acc_qvalid_o,
		.acc_qready_i,
		.acc_prsp_i,
		.acc_pvalid_i,
		.acc_pready_o,
		.x_issue_req_o(),
		.x_issue_resp_i('0),
		.x_issue_valid_o(),
		.x_issue_ready_i('0),
		.x_register_o(),
		.x_register_valid_o(),
		.x_register_ready_i('0),
		.x_commit_o(),
		.x_commit_valid_o(),
		.x_result_i('0),
		.x_result_valid_i('0),
		.x_result_ready_o(),
		.i2f_rdata_o(),
		.i2f_rvalid_o(),
		.i2f_rready_i('0),
		.f2i_wdata_i('0),
		.f2i_wvalid_i('0),
		.f2i_wready_o(),
		.data_req_o,
		.data_rsp_i,
		.ptw_valid_o(),
		.ptw_ready_i('0),
		.ptw_va_o(),
		.ptw_ppn_o(),
		.ptw_pte_i('0),
		.ptw_is_4mega_i('0),
		.fpu_rnd_mode_o,
		.fpu_fmt_mode_o,
		.fpu_status_i,
		.caq_pvalid_i,
		.core_events_o,
		.en_copift_o(),
		.barrier_o,
		.barrier_i
	);

endmodule