#!/usr/bin/env python3
# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Author: Pascal Etterli <petterli@student.ethz.ch>
"""Script to generate human-readable instruction traces for Schnizo.

This script takes a trace generated by a Schnizo hart
(see `schnizo.sv`) and transforms the additional decode stage info
into meaningful annotation.

It also counts and computes various performance metrics for every
execution region. An execution region is a sequence of instructions.
Every `mcycle` CSR read instruction in your trace implicitly defines
two execution regions, comprising respectively:

- all instructions executed before the read, up to the previous read
or the first executed instruction
- all instructions executed after the read, up to the next read or
the last executed instruction

Performance metrics are appended at the end of the generated trace
and can optionally be dumped to a separate JSON file.

It also computes various performance metrics for every DMA transfer,
provided that the Schnizo core is equipped with a tightly-coupled DMA
engine, and the DMA trace logged during simulation is fed to the tool.
DMA performance metrics are dumped to a separate JSON file.
"""

import sys
import argparse
import re
import ast
import json
import subprocess
from typing import Optional
from ctypes import c_int32, c_uint32
from functools import lru_cache
from collections import deque, defaultdict

import perfetto as perf

# -------------------- Tracer configuration  --------------------

CLOCK_PERIOD_NS = 1  # clock in nanoseconds

# Below this absolute value: use signed int representation. Above: unsigned 32-bit hex
MAX_SIGNED_INT_LIT = 0xFFFF

# Performance keys which only serve to compute other metrics: omit on printing
PERF_EVAL_KEYS_OMIT = ('start', 'end', 'end_fpss', 'snitch_issues',
                       'snitch_load_latency', 'snitch_fseq_offloads',
                       'fseq_issues', 'fpss_issues', 'fpss_fpu_issues',
                       'fpss_load_latency', 'fpss_fpu_latency', 'spatz_issues',)
PERF_EVAL_KEYS_DECIMAL = ('tstart', 'tend', 'cycles')

# -------------------- Architectural constants and enums  --------------------

REG_ABI_NAMES_I = ('zero', 'ra', 'sp', 'gp', 'tp', 't0', 't1', 't2', 's0',
                   's1', *('a{}'.format(i) for i in range(8)),
                   *('s{}'.format(i)
                     for i in range(2, 12)), *('t{}'.format(i)
                                               for i in range(3, 7)))

REG_ABI_NAMES_F = (*('ft{}'.format(i) for i in range(0, 8)), 'fs0', 'fs1',
                   'fa0', 'fa1', *('fa{}'.format(i) for i in range(2, 8)),
                   *('fs{}'.format(i)
                     for i in range(2, 12)), *('ft{}'.format(i)
                                               for i in range(8, 12)))

FLOAT_FMTS = ((8, 23), (11, 52), (5, 10), (5, 2), (8, 7), (4, 3))

LSU_SIZES = ('Byte', 'Half', 'Word', 'Doub')
LSU_SIZE_TO_FLOAT = (3, 2, 0, 1)

EVENT_DISPATCH = "dispatch"
EVENT_WRITEBACK = "writeback"
EVENT_RETIREMENT = "retirement"
EVENT_INTERNAL_SPATZ_ISSUE = "internal_spatz_issue"
EVENT_INTERNAL_SPATZ_RETIREMENT = "internal_spatz_retirement"
EVENT_RESREQ = "resreq"
EVENT_RESCAP = "rescap"

LOOP_REGULAR = "REG"
LOOP_HWLOOP = "HWL"
LOOP_LCP1 = "LCP1"
LOOP_LCP2 = "LCP2"
LOOP_LEP = "LEP"

FU_ALU = "ALU"
FU_LSU = "LSU"
FU_FPU = "FPU"
FU_CSR = "CSR"
FU_ACC = "ACC"
FU_MULDIV = "MULDIV"
FU_DMA = "DMA"
FU_SPATZ = "SPATZ"
FU_NONE = "NONE"

DASM_LINE_REGEX = r"^\s*(?P<sim_time>\d+)\s+(?P<cycle>\d+)\s+(?P<priv_lvl>[A-Z])\s+(?P<loop_state>[^\s]+)\s+#;\s+(?P<extra_str>.*?)(?=\s*$)"

CSR_MCYCLE = 'mcycle'

CSR_NAMES = {
    0xc00: 'cycle',
    0xc01: 'time',
    0xc02: 'instret',
    0xc03: 'hpmcounter3',
    0xc04: 'hpmcounter4',
    0xc05: 'hpmcounter5',
    0xc06: 'hpmcounter6',
    0xc07: 'hpmcounter7',
    0xc08: 'hpmcounter8',
    0xc09: 'hpmcounter9',
    0xc0a: 'hpmcounter10',
    0xc0b: 'hpmcounter11',
    0xc0c: 'hpmcounter12',
    0xc0d: 'hpmcounter13',
    0xc0e: 'hpmcounter14',
    0xc0f: 'hpmcounter15',
    0xc10: 'hpmcounter16',
    0xc11: 'hpmcounter17',
    0xc12: 'hpmcounter18',
    0xc13: 'hpmcounter19',
    0xc14: 'hpmcounter20',
    0xc15: 'hpmcounter21',
    0xc16: 'hpmcounter22',
    0xc17: 'hpmcounter23',
    0xc18: 'hpmcounter24',
    0xc19: 'hpmcounter25',
    0xc1a: 'hpmcounter26',
    0xc1b: 'hpmcounter27',
    0xc1c: 'hpmcounter28',
    0xc1d: 'hpmcounter29',
    0xc1e: 'hpmcounter30',
    0xc1f: 'hpmcounter31',
    0x100: 'sstatus',
    0x104: 'sie',
    0x105: 'stvec',
    0x106: 'scounteren',
    0x140: 'sscratch',
    0x141: 'sepc',
    0x142: 'scause',
    0x143: 'stval',
    0x144: 'sip',
    0x180: 'satp',
    0x200: 'bsstatus',
    0x204: 'bsie',
    0x205: 'bstvec',
    0x240: 'bsscratch',
    0x241: 'bsepc',
    0x242: 'bscause',
    0x243: 'bstval',
    0x244: 'bsip',
    0x280: 'bsatp',
    0xa00: 'hstatus',
    0xa02: 'hedeleg',
    0xa03: 'hideleg',
    0xa80: 'hgatp',
    0x7: 'utvt',
    0x45: 'unxti',
    0x46: 'uintstatus',
    0x48: 'uscratchcsw',
    0x49: 'uscratchcswl',
    0x107: 'stvt',
    0x145: 'snxti',
    0x146: 'sintstatus',
    0x148: 'sscratchcsw',
    0x149: 'sscratchcswl',
    0x307: 'mtvt',
    0x345: 'mnxti',
    0x346: 'mintstatus',
    0x348: 'mscratchcsw',
    0x349: 'mscratchcswl',
    0x300: 'mstatus',
    0x301: 'misa',
    0x302: 'medeleg',
    0x303: 'mideleg',
    0x304: 'mie',
    0x305: 'mtvec',
    0x306: 'mcounteren',
    0x340: 'mscratch',
    0x341: 'mepc',
    0x342: 'mcause',
    0x343: 'mtval',
    0x344: 'mip',
    0x3a0: 'pmpcfg0',
    0x3a1: 'pmpcfg1',
    0x3a2: 'pmpcfg2',
    0x3a3: 'pmpcfg3',
    0x3b0: 'pmpaddr0',
    0x3b1: 'pmpaddr1',
    0x3b2: 'pmpaddr2',
    0x3b3: 'pmpaddr3',
    0x3b4: 'pmpaddr4',
    0x3b5: 'pmpaddr5',
    0x3b6: 'pmpaddr6',
    0x3b7: 'pmpaddr7',
    0x3b8: 'pmpaddr8',
    0x3b9: 'pmpaddr9',
    0x3ba: 'pmpaddr10',
    0x3bb: 'pmpaddr11',
    0x3bc: 'pmpaddr12',
    0x3bd: 'pmpaddr13',
    0x3be: 'pmpaddr14',
    0x3bf: 'pmpaddr15',
    0x7a0: 'tselect',
    0x7a1: 'tdata1',
    0x7a2: 'tdata2',
    0x7a3: 'tdata3',
    0x7b0: 'dcsr',
    0x7b1: 'dpc',
    0x7b2: 'dscratch',
    0x7c2: 'cluster_barrier',
    0x7c4: 'frep_state',
    0x7c5: 'frep_config',
    0xb00: CSR_MCYCLE,
    0xb02: 'minstret',
    0xb03: 'mhpmcounter3',
    0xb04: 'mhpmcounter4',
    0xb05: 'mhpmcounter5',
    0xb06: 'mhpmcounter6',
    0xb07: 'mhpmcounter7',
    0xb08: 'mhpmcounter8',
    0xb09: 'mhpmcounter9',
    0xb0a: 'mhpmcounter10',
    0xb0b: 'mhpmcounter11',
    0xb0c: 'mhpmcounter12',
    0xb0d: 'mhpmcounter13',
    0xb0e: 'mhpmcounter14',
    0xb0f: 'mhpmcounter15',
    0xb10: 'mhpmcounter16',
    0xb11: 'mhpmcounter17',
    0xb12: 'mhpmcounter18',
    0xb13: 'mhpmcounter19',
    0xb14: 'mhpmcounter20',
    0xb15: 'mhpmcounter21',
    0xb16: 'mhpmcounter22',
    0xb17: 'mhpmcounter23',
    0xb18: 'mhpmcounter24',
    0xb19: 'mhpmcounter25',
    0xb1a: 'mhpmcounter26',
    0xb1b: 'mhpmcounter27',
    0xb1c: 'mhpmcounter28',
    0xb1d: 'mhpmcounter29',
    0xb1e: 'mhpmcounter30',
    0xb1f: 'mhpmcounter31',
    0x323: 'mhpmevent3',
    0x324: 'mhpmevent4',
    0x325: 'mhpmevent5',
    0x326: 'mhpmevent6',
    0x327: 'mhpmevent7',
    0x328: 'mhpmevent8',
    0x329: 'mhpmevent9',
    0x32a: 'mhpmevent10',
    0x32b: 'mhpmevent11',
    0x32c: 'mhpmevent12',
    0x32d: 'mhpmevent13',
    0x32e: 'mhpmevent14',
    0x32f: 'mhpmevent15',
    0x330: 'mhpmevent16',
    0x331: 'mhpmevent17',
    0x332: 'mhpmevent18',
    0x333: 'mhpmevent19',
    0x334: 'mhpmevent20',
    0x335: 'mhpmevent21',
    0x336: 'mhpmevent22',
    0x337: 'mhpmevent23',
    0x338: 'mhpmevent24',
    0x339: 'mhpmevent25',
    0x33a: 'mhpmevent26',
    0x33b: 'mhpmevent27',
    0x33c: 'mhpmevent28',
    0x33d: 'mhpmevent29',
    0x33e: 'mhpmevent30',
    0x33f: 'mhpmevent31',
    0xf11: 'mvendorid',
    0xf12: 'marchid',
    0xf13: 'mimpid',
    0xf14: 'mhartid',
    0xc80: 'cycleh',
    0xc81: 'timeh',
    0xc82: 'instreth',
    0xc83: 'hpmcounter3h',
    0xc84: 'hpmcounter4h',
    0xc85: 'hpmcounter5h',
    0xc86: 'hpmcounter6h',
    0xc87: 'hpmcounter7h',
    0xc88: 'hpmcounter8h',
    0xc89: 'hpmcounter9h',
    0xc8a: 'hpmcounter10h',
    0xc8b: 'hpmcounter11h',
    0xc8c: 'hpmcounter12h',
    0xc8d: 'hpmcounter13h',
    0xc8e: 'hpmcounter14h',
    0xc8f: 'hpmcounter15h',
    0xc90: 'hpmcounter16h',
    0xc91: 'hpmcounter17h',
    0xc92: 'hpmcounter18h',
    0xc93: 'hpmcounter19h',
    0xc94: 'hpmcounter20h',
    0xc95: 'hpmcounter21h',
    0xc96: 'hpmcounter22h',
    0xc97: 'hpmcounter23h',
    0xc98: 'hpmcounter24h',
    0xc99: 'hpmcounter25h',
    0xc9a: 'hpmcounter26h',
    0xc9b: 'hpmcounter27h',
    0xc9c: 'hpmcounter28h',
    0xc9d: 'hpmcounter29h',
    0xc9e: 'hpmcounter30h',
    0xc9f: 'hpmcounter31h',
    0xb80: 'mcycleh',
    0xb82: 'minstreth',
    0xb83: 'mhpmcounter3h',
    0xb84: 'mhpmcounter4h',
    0xb85: 'mhpmcounter5h',
    0xb86: 'mhpmcounter6h',
    0xb87: 'mhpmcounter7h',
    0xb88: 'mhpmcounter8h',
    0xb89: 'mhpmcounter9h',
    0xb8a: 'mhpmcounter10h',
    0xb8b: 'mhpmcounter11h',
    0xb8c: 'mhpmcounter12h',
    0xb8d: 'mhpmcounter13h',
    0xb8e: 'mhpmcounter14h',
    0xb8f: 'mhpmcounter15h',
    0xb90: 'mhpmcounter16h',
    0xb91: 'mhpmcounter17h',
    0xb92: 'mhpmcounter18h',
    0xb93: 'mhpmcounter19h',
    0xb94: 'mhpmcounter20h',
    0xb95: 'mhpmcounter21h',
    0xb96: 'mhpmcounter22h',
    0xb97: 'mhpmcounter23h',
    0xb98: 'mhpmcounter24h',
    0xb99: 'mhpmcounter25h',
    0xb9a: 'mhpmcounter26h',
    0xb9b: 'mhpmcounter27h',
    0xb9c: 'mhpmcounter28h',
    0xb9d: 'mhpmcounter29h',
    0xb9e: 'mhpmcounter30h',
    0xb9f: 'mhpmcounter31h'
}


# -------------------- helpers  --------------------------
def print_warning(message: str):
    sys.stderr.write(f"WARNING: {message}\n")


def print_fatal(message: str):
    sys.stderr.write(f"FATAL: {message}\n")


# -------------------- Float helpers  --------------------
def flt_decode(val: int, fmt: int) -> float:
    """Interprets the binary encoding of an integer as a FP value.

    Args:
        val: The integer encoding of the FP variable to decode.
        fmt: The floating point number format, as an index into the
            `FLOAT_FMTS` array.
    Returns:
        The floating point value represented by the input integer.
    """
    # get format and bit vector
    w_exp, w_mnt = FLOAT_FMTS[fmt]
    width = 1 + w_exp + w_mnt
    bitstr = '{:064b}'.format(val)[-width:]
    # print(bitstr)
    # Read bit vector slices
    sgn = -1.0 if bitstr[0] == '1' else 1.0
    mnt = int(bitstr[w_exp + 1:], 2)
    exp_unb = int(bitstr[1:w_exp + 1], 2)
    # derive base and exponent
    bse = int('1' + bitstr[w_exp + 1:], 2) / (2**w_mnt)
    exp_bias = -(2**(w_exp - 1) - 1)
    exp = exp_unb + exp_bias
    # case analysis
    if exp_unb == 2**w_exp - 1:
        return sgn * float('inf' if mnt == 0 else 'nan')
    elif exp_unb == 0 and mnt == 0:
        return sgn * 0.0
    elif exp_unb == 0:
        return float(sgn * mnt / (2**w_mnt) * (2**(exp_bias + 1)))
    else:
        return float(sgn * bse * (2**exp))


def flt_fmt(flt: float, width: int = 6) -> str:
    """Formats a floating-point number rounding to a certain decimal precision.

    Args:
        flt: The floating-point number to format.
        width: The number of significant decimal digits to round to.
    Returns:
        The formatted floating-point number as a string.
    """
    fmt = '{:.' + str(width) + '}'
    return fmt.format(flt)


# -------------------- Literal formatting  --------------------
def int_lit(num: int, size: int = 2, as_hex: Optional[bool] = None, prefix: Optional[bool] = True) -> str:
    width = (8 * int(2**size))
    size_mask = (0x1 << width) - 1
    num = num & size_mask  # num is unsigned
    num_signed = c_int32(c_uint32(num).value).value
    if as_hex is True or abs(num_signed) > MAX_SIGNED_INT_LIT and as_hex is not False:
        if prefix is True:
            return '0x{0:0{1}x}'.format(num, width // 4)
        else:
            return '{0:0{1}x}'.format(num, width // 4)
    else:
        return str(num_signed)


def flt_lit(num: int, fmt: int, width: int = 6, vlen: int = 1) -> str:
    """Formats an integer encoding into a floating-point literal.

    Args:
        num: The integer encoding of the floating-point number(s).
        fmt: The floating point number format, as an index into the
            `FLOAT_FMTS` array.
        width: The bitwidth of the floating-point type.
        vlen: The number of floating-point numbers packed in the encoding,
            >1 for SIMD vectors.
    """
    # Divide the binary encoding into individual encodings for each number in the SIMD vector.
    bitwidth = 1 + FLOAT_FMTS[fmt][0] + FLOAT_FMTS[fmt][1]
    vec = [num >> (bitwidth * i) & (2**bitwidth - 1) for i in reversed(range(vlen))]
    # Format each individual float encoding to a string.
    floats = [flt_fmt(flt_decode(val, fmt), width) for val in vec]
    # Represent the encodings as a vector if SIMD.
    if len(floats) > 1:
        return '[{}]'.format(', '.join(floats))
    else:
        return floats[0]


@lru_cache
def disasm_inst(hex_inst, mc_exec='llvm-mc', mc_flags='-disassemble -mcpu=snitch -mattr=+v'):
    """Disassemble a single RISC-V instruction using llvm-mc."""
    # Reverse the endianness of the hex instruction
    inst_fmt = ' '.join(f'0x{byte:02x}' for byte in bytes.fromhex(hex_inst)[::-1])

    # Use llvm-mc to disassemble the binary instruction
    result = subprocess.run(
        [mc_exec] + mc_flags.split(),
        input=inst_fmt,
        capture_output=True,
        text=True,
        check=True,
    )

    # Extract disassembled instruction from llvm-mc output
    return result.stdout.splitlines()[-1].strip().replace('\t', ' ')


def parse_cycle(line: str) -> int:
    match = re.match(DASM_LINE_REGEX, line)
    if match:
        return match.group("cycle")
    else:
        raise ValueError(f"Not a valid trace line:\n{line}")


# Takes a DASM event line and parses it. Returns a tuple of::
# time: The current sim time
# cycle: The current cycle
# priv_lvl: The CPU privilege level
# loop_state: FREP loop state
# extras: Dict with extra data depending on event
def parse_event(line: str) -> tuple[int, int, str, str, dict]:
    match = re.match(DASM_LINE_REGEX, line)
    if match:
        # Extract the named groups
        sim_time = int(match.group("sim_time"))
        cycle = int(match.group("cycle"))
        priv_lvl = match.group("priv_lvl")
        loop_state = match.group("loop_state")
        extra_str = match.group("extra_str").strip("{}")

        # Convert the extra string to a dict
        extras = ast.literal_eval(f"{{{extra_str}}}")
        return sim_time, cycle, priv_lvl, loop_state, extras
    else:
        raise ValueError(f"Not a valid trace line:\n{line}")


# Parses the mnemomic, pc, rs2 and rd from dispatch extras.
# !! MUST BE a "Regular" dispatch event !! (LOOP_REGULAR, LOOP_HWLOOP, LOOP_LCP1, LOOP_LCP2)
def parse_mnemomic_from_dispatch(extras: dict, mc_exec: str) -> tuple[str, str, int, int]:
    mnemomic = disasm_inst(int_lit(extras['instr_data'], as_hex=True, prefix=False), mc_exec)
    pc_str = int_lit(extras['pc_q'], as_hex=True)
    rs2 = extras['rs2']
    rd = extras['rd']

    return pc_str, mnemomic, rs2, rd


# producers is a dict with key "producer" and a tuple containing
# pc_str, mnemomic, rs2, rd, iter_count
def gen_dispatch_trace(loop_state, extras, producers, mc_exec) -> str:
    if (loop_state in {LOOP_REGULAR, LOOP_HWLOOP, LOOP_LCP1, LOOP_LCP2}):
        pc_str, mnemomic, rs2, rd = parse_mnemomic_from_dispatch(extras, mc_exec)
        iter_count = 1

        # FREP producer mapping for LEP trace details
        # Reset mapping in Regular, HW loop & LCP1
        # (If nested: create new mapping when entering LCP1)
        # Build mapping in LCP2
        # Don't change mapping during LEP
        # (If nested: destroy mapping when leaving LEP)
        if (loop_state in {LOOP_REGULAR, LOOP_HWLOOP, LOOP_LCP1}):
            producers = {}
        elif (loop_state in {LOOP_LCP2}):
            pc_str, mnemomic, rs2, rd = parse_mnemomic_from_dispatch(extras, mc_exec)
            # start the iteration count after two iterations
            iter_count = 2
            producers[extras['disp_resp']] = (pc_str, mnemomic, rs2, rd, iter_count)

        fu_str = extras['disp_resp']
    elif loop_state in {LOOP_LEP}:
        fu_str = extras['producer']
        if (extras['producer'] in producers):
            pc_str, mnemomic, rs2, rd, iter_count = producers[extras['producer']]
            # incremetn the interation count for this producer
            iter_count += 1
            producers[extras['producer']] = (pc_str, mnemomic, rs2, rd, iter_count)
        else:
            mnemomic = "no lep data"
            pc_str = "0x????????"
            rs2 = 0
            rd = 0
            iter_count = 0
    else:
        raise ValueError(f"Not a valid loop state:{loop_state}\n")

    # Don't print the fu if in regular mode
    if (loop_state not in {LOOP_LCP1, LOOP_LCP2, LOOP_LEP}):
        fu_str = ""
    txt = f"{pc_str:<10} {mnemomic:<26}  {fu_str:<6} #; "

    # LSU
    is_lsu = False
    if ('fu_type' in extras):
        is_lsu = extras['fu_type'] in {FU_LSU}
    elif ('producer' in extras):
        is_lsu = extras['producer'].startswith(FU_LSU)

    comment = []
    # LSU
    if (is_lsu):
        if (extras['lsu_is_store']):
            register = REG_ABI_NAMES_F[rs2] if extras['lsu_is_float'] else REG_ABI_NAMES_I[rs2]
            fmt = LSU_SIZE_TO_FLOAT[extras['lsu_size']]
            value_str = flt_lit(extras['lsu_store_data'], fmt) if extras['lsu_is_float'] else int_lit(extras['lsu_store_data'])
            comment.append(f"{register} = {value_str} ~~> {LSU_SIZES[extras['lsu_size']]}[{int_lit(extras['lsu_addr'], as_hex=True)}]")
        elif (extras['lsu_is_load']):
            register = REG_ABI_NAMES_F[rd] if extras['lsu_is_float'] else REG_ABI_NAMES_I[rd]
            comment.append(f"{register} <~~ {LSU_SIZES[extras['lsu_size']]}[{int_lit(extras['lsu_addr'], as_hex=True)}]")
    # CSR
    if ('fu_type' in extras):
        if (extras['fu_type'] == FU_CSR):
            csr_name = CSR_NAMES[extras['csr_addr']] if extras['csr_addr'] in CSR_NAMES else f"csr@{int_lit(extras['csr_addr'], as_hex=True)}"
            comment.append(f"{csr_name} = {int_lit(extras['csr_write_data'])}")
    # Branch?
    if (extras.get('is_branch', False)):
        comment.append("taken" if extras['branch_taken'] else "not taken")
    # Jump?
    if not extras['stall'] and (extras.get('pc_d', 4) != (extras.get('pc_q', 0) + 4)):
        comment.append(f"goto {int_lit(extras['pc_d'], as_hex=True)}")
    # Instruction iter if in FREP
    if (('instr_iter' in extras) and loop_state in {LOOP_LCP1, LOOP_LCP2, LOOP_LEP}):
        comment.append(f"instr iter = {iter_count} ({extras['instr_iter']})")

    txt += ", ".join(comment)
    return txt


# flt_fmt is the float format if we have a writeback in this cycle.
# This values must come from the state handling logic as the DASM cannot provide it.
def gen_writeback_trace(extras):
    flt_fmt = 0  # TODO: somehow get the flt format?
    register = REG_ABI_NAMES_F[extras['rd']] if extras['rd_is_fp'] else REG_ABI_NAMES_I[extras['rd']]
    value_str = flt_lit(extras['result'], flt_fmt) if extras['rd_is_fp'] else int_lit(extras['result'])
    writeback = f"{register} = {value_str}"
    if (extras['rd'] == 0 and not extras['rd_is_fp']):
        # This is a writeback to GPR 0, which is fixed to all zeros. Schnizo uses dummy writebacks
        # to this GPR for instructions which don't write any registers.
        return ""
    return f"{'':<10} {'':<26}  {'':<6} #; {extras['origin']}: {writeback}"


def gen_resreq_trace(extras):
    return f"{'':<10} {'':<26}  {'':<6} #; RESREQ to {extras['producer']} from {extras['consumer']}, result iter = {extras['requested_iter']}"


def gen_rescap_trace(extras):
    return f"{'':<10} {'':<26}  {'':<6} #; RESCAP {extras['producer']} <-- {int_lit(extras['result'])} {'(float)' if extras['rd_is_fp'] else ''}, result iter = {extras['result_iter']}"


def handle_dispatch_event(sim_time, cycle, priv_lvl, loop_state, extras,
                          lsu_pipelines, fpu_pipelines, perf_metrics):
    if extras['stall'] and not (loop_state in {LOOP_LEP}):
        return

    perf_metrics[-1]['schnizo_issues'] += 1

    # CSR
    if ('fu_type' in extras):
        if (extras['fu_type'] == FU_CSR):
            csr_addr = extras['csr_addr']
            csr_name = CSR_NAMES[csr_addr] if csr_addr in CSR_NAMES else ""
            if csr_name == CSR_MCYCLE:
                # Schnizo only supports reading the mcycle CSR despite in the RISCV standard it is MRW.
                cycles_passed = extras['csr_read_data']
                perf_metrics[-1]['tend'] = sim_time // 1000
                perf_metrics[-1]['end'] = cycles_passed  # does not include the current cycle
                perf_metrics.append(defaultdict(int))
                perf_metrics[-1]['tstart'] = sim_time // 1000
                perf_metrics[-1]['start'] = cycles_passed + 2  # next section starts from next cycle onwards

    # FPU
    is_fpu = False
    if ('fu_type' in extras):
        is_fpu = extras['fu_type'] in {FU_FPU}
        fpu_id = extras['disp_resp'].split('.')[0]
    elif ('producer' in extras):
        is_fpu = extras['producer'].startswith(FU_FPU)
        fpu_id = extras['producer'].split('.')[0]

    if (is_fpu):
        perf_metrics[-1]['schnizo_fpu_issues'] += 1
        fpu_pipelines[fpu_id].appendleft((cycle, LSU_SIZE_TO_FLOAT[extras['fpu_dst_fmt']]))

    # LSU
    is_lsu = False
    lsu_id = ""
    if ('fu_type' in extras):
        is_lsu = extras['disp_resp'].startswith(FU_LSU)
        # keep only the first characters and all number until the first .
        lsu_id = extras['disp_resp'].split('.')[0]
    elif ('producer' in extras):
        is_lsu = extras['producer'].startswith(FU_LSU)
        lsu_id = extras['producer'].split('.')[0]

    if (is_lsu):
        if (extras['lsu_is_load']):
            perf_metrics[-1]['schnizo_loads'] += 1
            lsu_pipelines[lsu_id].appendleft((cycle, extras['lsu_is_float']))
            if (extras['lsu_is_float']):  # save also float format for writeback float literal
                perf_metrics[-1]['schnizo_fpr_loads'] += 1
            else:
                perf_metrics[-1]['schnizo_gpr_loads'] += 1
        elif (extras['lsu_is_store']):
            perf_metrics[-1]['schnizo_stores'] += 1
            if (extras['lsu_is_float']):
                perf_metrics[-1]['schnizo_fpr_stores'] += 1
            else:
                perf_metrics[-1]['schnizo_gpr_stores'] += 1


    is_spatz = False
    if ('fu_type' in extras):
        is_spatz = extras['fu_type'] in {FU_SPATZ}
    elif ('producer' in extras):
        is_spatz = extras['producer'].startswith(FU_SPATZ)
    
    if (is_spatz):
        perf_metrics[-1]['spatz_issues'] += 1

    return 0


# TODO: Track the latency of spatz operations as well.

def handle_retirement_event(cycle, priv_lvl, loop_state, extras,
                            lsu_pipelines, fpu_pipelines, perf_metrics, permissive):
    if (extras['producer'].startswith(FU_LSU) or extras['producer'].startswith(FU_FPU)):
        try:
            fu_id = extras['producer'].split('.')[0]
            if (extras['producer'].startswith(FU_LSU)):
                start_time, is_fp = lsu_pipelines[fu_id].pop()
                # We define the latency as the number of cycles we need, i.e., the duration
                # Thus we do +1
                latency = cycle - start_time + 1
                perf_metrics[-1]['schnizo_load_latency'] += latency
                if (is_fp):
                    perf_metrics[-1]['schnizo_fpr_load_latency'] += latency
                else:
                    perf_metrics[-1]['schnizo_gpr_load_latency'] += latency
            if (extras['producer'].startswith(FU_FPU)):
                start_time, _ = fpu_pipelines[fu_id].pop()
                latency = cycle - start_time + 1
                perf_metrics[-1]['schnizo_fpu_latency'] += latency
        except IndexError:
            message = f"Retirement: In cycle {cycle}, {extras['producer']} tried to retire, but no load is in flight."
            if permissive:
                print_warning(message)
            else:
                print_fatal(message)
                sys.exit(222)
    return 0


def gen_dispatch_perfetto(sim_time, cycle, priv_lvl, loop_state, extras,
                          all_tracks, inflight_tracks, perf_events, producers, mc_exec):
    if extras['stall'] and not (loop_state in {LOOP_LEP}):
        return

    if (loop_state in {LOOP_REGULAR, LOOP_HWLOOP, LOOP_LCP1, LOOP_LCP2}):
        pc_str, mnemomic, _, _ = parse_mnemomic_from_dispatch(extras, mc_exec)
        iter_count = 0
        fu_str = extras['disp_resp']
        # in regular mode we cannot distinguish between producers.
        # if (loop_state not in {LOOP_LCP1, LOOP_LCP2}):
        #     fu_str = fu_str.split('.')[0]
        # Dispatch response is invalid for CSR, MULDIV, DMA and  NONE
        fu_type = extras['fu_type']
        if (fu_type in {FU_CSR, FU_MULDIV, FU_DMA, FU_NONE}):
            fu_str = fu_type
            # We don't have infos about the accelerator id at retirement. Thus map everything to ACC.
            if (fu_type in {FU_MULDIV, FU_DMA}):
                fu_str = FU_ACC
    elif loop_state in {LOOP_LEP}:
        fu_str = extras['producer']
        if (extras['producer'] in producers):
            pc_str, mnemomic, _, _, iter_count = producers[extras['producer']]
        else:
            mnemomic = "no lep data"
            pc_str = "0x????????"
            iter_count = 0
    else:
        raise ValueError(f"Not a valid loop state: {loop_state}\n")

    # Emit the perfetto event
    if (loop_state == LOOP_LCP1):
        iter_count = 1
    elif (loop_state == LOOP_LCP2):
        iter_count = 2
    if (loop_state in {LOOP_LCP1, LOOP_LCP2, LOOP_LEP}):
        instr_str = f"iter {iter_count}: {mnemomic} ({pc_str})"
    else:
        instr_str = f"{mnemomic} ({pc_str})"

    perf_events.append(perf.start_instr(fu_str, instr_str,
                                        cycle * CLOCK_PERIOD_NS, all_tracks, inflight_tracks))
    # Immediately end instructions for FU_NONE as there is no retirement event.
    if (fu_str == FU_NONE):
        # The instruction ends in this cycle. Thus the event is at the end of this cycle.
        perf_events.append(perf.end_instr(fu_str, (cycle+1) * CLOCK_PERIOD_NS,
                                          all_tracks, inflight_tracks))
    # Immediately end store instructions as there is no retirement event.
    elif (fu_str.startswith(FU_LSU)):
        if (extras['lsu_is_store']):
            # The instruction ends in this cycle. Thus the event is at the end of this cycle.
            perf_events.append(perf.end_instr(fu_str, (cycle+1) * CLOCK_PERIOD_NS,
                                              all_tracks, inflight_tracks))
    elif (fu_str.startswith(FU_SPATZ)):
            perf_events.append(perf.end_instr(fu_str, (cycle+1) * CLOCK_PERIOD_NS,
                                              all_tracks, inflight_tracks))
            


def gen_retirement_perfetto(sim_time, cycle, priv_lvl, loop_state, extras,
                            all_tracks, inflight_tracks, perf_events):
    # Only capture the retirement in regular modes.
    # During FREP modes we capture with the rescap event because we need the producer id.

    if (loop_state in {LOOP_REGULAR, LOOP_HWLOOP}):
        fu_str = extras['producer']
        # We map all instructions to the first FU of its type. Except for CSR,
        # MULDIV, DMA (combined to ACC) and NONE.
        if (fu_str not in {FU_CSR, FU_ACC, FU_NONE}):
            fu_str = f"{fu_str}.0"
        # The instruction ends in this cycle. Thus the event is at the end of this cycle.
        perf_events.append(perf.end_instr(fu_str, (cycle+1) * CLOCK_PERIOD_NS,
                                          all_tracks, inflight_tracks))


def gen_rescap_perfetto(sim_time, cycle, priv_lvl, loop_state, extras,
                        all_tracks, inflight_tracks, perf_events):
    fu_str = extras['producer']
    if not fu_str.startswith('SPATZ'):
        # The instruction ends in this cycle. Thus the event is at the end of this cycle.
        perf_events.append(perf.end_instr(fu_str, (cycle+1) * CLOCK_PERIOD_NS,
                                      all_tracks, inflight_tracks))

# TODO: Maybe trying to be more consistent with the naming
def gen_int_spatz_issue_perfetto(cycle, extras,
                                 all_tracks, inflight_tracks, perf_events):
    fu_str = f"INSPATZ0.{extras['id']}"
    instr_str = f"{extras['op']}"
    perf_events.append(perf.start_instr(fu_str, instr_str,
                                        cycle * CLOCK_PERIOD_NS, all_tracks, inflight_tracks))

def gen_int_spatz_retirement_perfetto(cycle, extras,
                                     all_tracks, inflight_tracks, perf_events):
    fu_str = f"INSPATZ0.{extras['id']}"
    # The instruction ends in this cycle. Thus the event is at the end of this cycle.
    print(extras)
    perf_events.append(perf.end_instr(fu_str, (cycle+1) * CLOCK_PERIOD_NS,
                                      all_tracks, inflight_tracks))

def gen_trace_line(line, mc_exec,
                   lsu_pipelines, fpu_pipelines,
                   all_tracks, inflight_tracks, perf_events,
                   perf_metrics, producers, permissive) -> tuple[str, int, int]:
    sim_time, cycle, priv_lvl, loop_state, extras = parse_event(line)

    # Update stateful structures
    # We need to know
    # - In flight instructions to measure the latency of loads/stores
    # - instruction to producer mappings after LCP2 (for all instructions we must know the producer) -> ALU0.0 : addi t0, xcvxv
    #     This way we can print the nmemonics also during LEP
    # - the format of the currently written back float value

    # Performance data
    # - start / stop between mcycle CSR reads
    # - the total number of
    #    - instruction issues
    #    - stores / loads (separate for int and fp)
    #    - fpu instruction issues
    # - Store / Load latency of int and fp

    # FREP visualization
    # Each FREP loop generates a TraceEvent json file
    # We need to track all instructions.

    header = f"{sim_time:>8}  {cycle:>6}  {priv_lvl} {loop_state:<4} "  # trailing space
    trace_body = ""
    if (extras['event'] == EVENT_DISPATCH):
        handle_dispatch_event(sim_time, cycle, priv_lvl, loop_state, extras,
                              lsu_pipelines, fpu_pipelines,
                              perf_metrics)
        trace_body = gen_dispatch_trace(loop_state, extras, producers, mc_exec)
        gen_dispatch_perfetto(sim_time, cycle, priv_lvl, loop_state, extras,
                              all_tracks, inflight_tracks, perf_events, producers, mc_exec)
    elif (extras['event'] == EVENT_WRITEBACK):
        # Nothing statefull to handle - TODO: extract somehow the float format..
        trace_body = gen_writeback_trace(extras)
    elif (extras['event'] == EVENT_RESREQ):
        # Nothing statefull to handle
        trace_body = gen_resreq_trace(extras)
    elif (extras['event'] == EVENT_RESCAP):
        trace_body = gen_rescap_trace(extras)
        gen_rescap_perfetto(sim_time, cycle, priv_lvl, loop_state, extras,
                            all_tracks, inflight_tracks, perf_events)
    elif (extras['event'] == EVENT_RETIREMENT):
        handle_retirement_event(cycle, priv_lvl, loop_state, extras,
                                lsu_pipelines, fpu_pipelines, perf_metrics, permissive)
        gen_retirement_perfetto(sim_time, cycle, priv_lvl, loop_state, extras,
                                all_tracks, inflight_tracks, perf_events)
    elif (extras['event'] == EVENT_INTERNAL_SPATZ_ISSUE):
        gen_int_spatz_issue_perfetto(cycle, extras,
                                     all_tracks, inflight_tracks, perf_events)
    elif (extras['event'] == EVENT_INTERNAL_SPATZ_RETIREMENT):
        gen_int_spatz_retirement_perfetto(cycle, extras,
                                         all_tracks, inflight_tracks, perf_events)
    else:
        raise ValueError(f"Not a valid event type: {extras['event']}\n")

    if ((not extras['stall']) and extras['exception']):
        trace_body += " EXCEPTION"

    if (trace_body == ""):
        trace_line = ""
    else:
        trace_line = header + trace_body + "\n"

    return trace_line, sim_time, cycle


def safe_div(dividend, divisor, zero_div=0):
    return dividend / divisor if divisor else zero_div


def eval_perf_metrics(perf_metrics: list):
    for seg in perf_metrics:
        end = seg['end']
        # TODO: Add latency of FPU because at the end a FPU instruction could still be in flight.
        cycles = end - seg['start'] + 1  # +1 includes the csr read ending the segment
        seg.update({
            'schnizo_fpu_occupancy':
                safe_div(seg['schnizo_fpu_issues'], cycles),
            'schnizo_fpu_avg_latency':
                safe_div(seg['schnizo_fpu_latency'], seg['schnizo_fpu_issues']),
            'schnizo_avg_load_latency':
                safe_div(seg['schnizo_load_latency'], seg['schnizo_loads']),
            'schnizo_avg_gpr_load_latency':
                safe_div(seg['schnizo_gpr_load_latency'], seg['schnizo_gpr_loads']),
            'schnizo_avg_fpr_load_latency':
                safe_div(seg['schnizo_fpr_load_latency'], seg['schnizo_fpr_loads']),
            'cycles':
                cycles,
            'total_ipc':
                safe_div(seg['schnizo_issues'], cycles),
        })
    return 0


def fmt_perf_metrics(perf_metrics: list, idx: int, omit_keys: bool = True):
    ret = [
        'Performance metrics for section {} @ ({}, {}):'.format(
            idx, perf_metrics[idx]['start'], perf_metrics[idx]['end'])
    ]
    for key, val in perf_metrics[idx].items():
        if omit_keys and key in PERF_EVAL_KEYS_OMIT:
            continue
        if val is None:
            val_str = str(None)
        elif isinstance(val, float):
            val_str = flt_fmt(val, 4)
        else:
            as_hex = False if key in PERF_EVAL_KEYS_DECIMAL else None
            val_str = int_lit(val, as_hex=as_hex)
        ret.append('{:<40}{:>10}'.format(key, val_str))
    return '\n'.join(ret)


# -------------------- Main --------------------
# noinspection PyTypeChecker
def main():
    # Argument parsing and iterator creation
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'infile',
        metavar='infile.dasm',
        nargs='?',
        type=argparse.FileType('r'),
        default=sys.stdin,
        help='A matching ASCII signal dump',
    )
    parser.add_argument(
        '-o',
        '--output',
        required=True,
        type=argparse.FileType('w'),
        help='Path to the output file'
    )
    parser.add_argument(
        '--offl',
        action='store_true',
        help='Annotate FPSS and sequencer offloads when they happen in core')
    parser.add_argument(
        '-s',
        '--saddr',
        action='store_true',
        help='Use signed decimal (not unsigned hex) for small addresses')
    parser.add_argument(
        '-a',
        '--allkeys',
        action='store_true',
        help='Include performance metrics measured to compute others')
    parser.add_argument(
        '-p',
        '--permissive',
        action='store_true',
        help='Ignore some state-related issues when they occur')
    parser.add_argument(
        '--dma-trace',
        help='Path to a DMA trace file'
    )
    parser.add_argument(
        '--dump-hart-perf',
        nargs='?',
        type=argparse.FileType('w'),
        help='Dump hart performance metrics as json text.'
    )
    parser.add_argument(
        '--dump-dma-perf',
        help='Dump DMA performance metrics as json text.'
    )
    parser.add_argument(
        '--perfetto-trace',
        nargs='?',
        type=argparse.FileType('wb'),
        help='Path to the perfetto trace file as protobuf.'
    )
    parser.add_argument(
        '--mc-exec',
        default='llvm-mc',
        help='Path to the llvm-mc executable'
    )
    parser.add_argument(
        '--mc-flags',
        default='-disassemble -mcpu=snitch',
        help='Flags to pass to the llvm-mc executable'
    )

    args = parser.parse_args()

    # Trace structures
    all_tracks = defaultdict()
    inflight_tracks = defaultdict(deque)
    perf_events = []

    with args.output as trace_file:
        # Setup stateful structures
        # Dicts to store information about LSU pipeline (for latency). A dict for each LSU.
        lsu_pipelines = defaultdict(deque)
        fpu_pipelines = defaultdict(deque)
        # Dict to store the instruction to producer mapping for LEP trace data
        producers = {}
        # Various performance metrics of the core
        perf_metrics = [
            defaultdict(int)
        ]  # all values initially 0, also 'start' time of measurement 0
        perf_metrics[0]['start'] = None

        # dma_trans = [{'rep': 1}]

        is_first_cycle = True
        for line in args.infile:
            # Process each event independently
            trace_line, sim_time, cycle = gen_trace_line(line, args.mc_exec,
                                                         lsu_pipelines, fpu_pipelines,
                                                         all_tracks, inflight_tracks, perf_events,
                                                         perf_metrics, producers, args.permissive)
            # The newline character is in the trace line. This way the trace line can also be empty.
            print(trace_line, file=trace_file, end="")

            # Add artificial delay event to synchronize Perfetto with the cycle time
            if is_first_cycle:
                start, end = perf.add_start_offset(cycle * CLOCK_PERIOD_NS, all_tracks)
                perf_events.append(start)
                perf_events.append(end)
                is_first_cycle = False

            if perf_metrics[0]['start'] is None:
                perf_metrics[0]['tstart'] = sim_time // 1000
                perf_metrics[0]['start'] = cycle

        perf_metrics[-1]['tend'] = sim_time // 1000
        perf_metrics[-1]['end'] = cycle

        # Performance metrics
        eval_perf_metrics(perf_metrics)
        print('\n## Performance metrics', file=trace_file)
        for idx in range(len(perf_metrics)):
            print('\n' + fmt_perf_metrics(perf_metrics, idx, not args.allkeys), file=trace_file)

    # Emit trace
    if args.perfetto_trace:
        with args.perfetto_trace as perfetto_file:
            perfetto_trace = perf.create_trace(all_tracks, perf_events)
            perf.write_trace_to_file(perfetto_trace, perfetto_file)

    # Emit DMA metrics
    # if args.dma_trace:
    #     dma_metrics = eval_dma_metrics(dma_trans, args.dma_trace)

    # Dump hart performance metrics to JSON file
    if args.dump_hart_perf:
        with args.dump_hart_perf as file:
            file.write(json.dumps(perf_metrics, indent=4))
    # # Dump DMA performance metrics to JSON file
    # if args.dump_dma_perf and dma_metrics is not None:
    #     with open(args.dump_dma_perf, 'w') as file:
    #         file.write(json.dumps(dma_metrics, indent=4))

    # Check for any unfinished instructions
    for lsu, pipeline in lsu_pipelines.items():
        if len(pipeline) != 0:
            print_warning(f"{len(pipeline)} unfinished load operations detected for {lsu}.")

    for fpu, pipeline in fpu_pipelines.items():
        if len(pipeline) != 0:
            print_warning(f"{len(pipeline)} unfinished operations detected for {fpu}.")


    return 0


if __name__ == '__main__':
    sys.exit(main())


# Experiment

    # Process all events and group them by cycle number
    # with args.output as trace_file:
    #     # Group lines by cycle and process them together
    #     current_cycle = None
    #     grouped_lines = []

    #     while True:
    #         line = args.infile.readline()
    #         if not line:
    #             break  # End of file

    #         cycle = parse_cycle(line)

    #         if current_cycle is None:
    #             current_cycle = cycle

    #         if cycle == current_cycle:
    #             grouped_lines.append(line)
    #         else:
    #             # Process all lines for the current cycle
    #             process_samecycle_lines(grouped_lines, trace_file, args.mc_exec)
    #             # Reset for the next cycle
    #             current_cycle = cycle
    #             grouped_lines = [line]

    #     # Process any remaining events
    #     if grouped_lines:
    #         process_samecycle_lines(grouped_lines, trace_file, args.mc_exec)

# def process_samecycle_lines(lines, trace_file, mc_exec):
#     # Parse all lines and convert them to events using the parse_event() function
#     events = [parse_event(line) for line in lines]

#     # Check if all events are in the same loop_state
#     loop_states = {event[3] for event in events}  # Extract loop_state from each event
#     if len(loop_states) > 1:
#         raise ValueError("Events in the same cycle have different loop states.")

#     # resreqs are handled always serially TODO

#     # TODO: we pass events instead of lines...
#     # If in single issue (LOOP_REGULAR, LOOP_HWLOOP, LOOP_LCP1 & LOOP_LCP2) combine dispatch & writeback onto one line.
#     # If there are more than 1 writebacks, add all successive writebacks on a separate line
#     if loop_states.issubset({LOOP_REGULAR, LOOP_HWLOOP, LOOP_LCP1, LOOP_LCP2}):
#         dispatch_event = next((event for event in events if event[4]['event'] == "dispatch"), None)
#         writeback_events = [event for event in events if event[4]['event'] == "writeback"]

#         if dispatch_event:
#             trace_line = generator(dispatch_event, mc_exec)
#             if writeback_events:
#                 writeback_traces = [
#                     gen_writeback_trace(writeback_event[4], 0) for writeback_event in writeback_events
#                 ]
#                 trace_line += " | " + " | ".join(writeback_traces)
#                 print(trace_line, file=trace_file)
#         elif writeback_events:
#             for writeback_event in writeback_events:
#                 trace_line = generator(writeback_event, mc_exec)
#         print(trace_line, file=trace_file)

#         # Handle additional writebacks on separate lines
#         for writeback_event in writeback_events[1:]:
#             trace_line = generator(writeback_event, mc_exec)
#             print(trace_line, file=trace_file)
#     else:
#         # Generate trace lines for each event and write them to the output file
#         for event in events:
#             trace_line = generator(event, mc_exec)
#             print(trace_line, file=trace_file)

#     # Generate trace lines for each event and write them to the output file
#     for event in events:
#         trace_line = generator(event, mc_exec)
#         print(trace_line, file=trace_file)